config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :beers do 
    resources :reviews
  end
  
  root 'beers#index'
end

app/models/beer.rb
class Beer < ActiveRecord::Base
    belongs_to :user
    belongs_to :category 
    belongs_to :brewery
    has_many :reviews 
    
    
    has_attached_file :beer_img, :styles => { :beer_index => "250x350>", :beer_show => "325x475>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :beer_img, :content_type => /\Aimage\/.*\Z/
end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
    has_many :beers
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :beers
end

app/models/review.rb
class Review < ActiveRecord::Base
    belongs_to :beer
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :beers
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
    before_action :find_beer, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :edit]
    
    def index
        if params[:category].blank?
            @beers = Beer.all.order("created_at DESC")
        else
            @category_id = Category.find_by(name: params[:category]).id
            @beers = Beer.where(:category_id => @category_id).order("created_at DESC")
        end
    end
    
    def show
        if @beer.reviews.blank?
            @average_review = 0
        else
            @average_review = @beer.reviews.average(:rating).round(2)
        end
    end
    
    def new
        @beer = current_user.beers.build
        @categories = Category.all.map{ |c| [c.name, c.id] }
        @breweries = Brewery.all.map{ |c| [c.name, c.id] }
    end
    
    def create
        @beer = current_user.beers.build(beer_params)
        @beer.category_id = params[:category_id]
        @beer.brewery_id = params[:brewery_id]
        
        if @beer.save
            redirect_to root_path
        else
            render 'new'
        end
    end
    
    def edit
        @categories = Category.all.map{ |c| [c.name, c.id] }
        @breweries = Brewery.all.map{ |c| [c.name, c.id] }
    end
    
    def update
        @beer.category_id = params[:category_id]
        @beer.brewery_id = params[:brewery_id]
        if @beer.update(beer_params)
            redirect_to @beer
        else
            render 'edit'
        end
    end
    
    def destroy
        @beer.destroy
        redirect_to root_path
    end
    
    private
        
        def beer_params
            params.require(:beer).permit(:name, :description, :category_id, :beer_img, :brewery_id)
        end
        
        def find_beer
            @beer = Beer.find(params[:id])
        end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :find_beer
    before_action :find_review, only: [:edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :edit]
    
    def new
        @review = Review.new
    end
    
    def create
        @review = Review.new(review_params)
        @review.beer_id = @beer.id
        @review.user_id = current_user.id
        
        if @review.save
            redirect_to @beer
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @review.update(review_params)
            redirect_to @beer
        else 
            render 'edit'
        end
    end
    
    def destroy
        @review.destroy
        redirect_to @beer
    end
    
    private
        def review_params
            params.require(:review).permit(:rating, :comment)
        end
        
        def find_beer
            @beer = Beer.find(params[:beer_id])
        end
        
        def find_review
            @review = Review.find(params[:id])
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beer_helper.rb
module BeerHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/beers/_form.html.erb
<%= simple_form_for @beer, :html => { multipart: true } do |f| %>
    <%= f.label :beer_img, 'Image' %>
    <%= f.file_field :beer_img %>
    <%= f.label :category_id, 'Category' %>
    <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a Category", html: { class: 'chosen'} )%><br />
    <%= f.label :brewery_id, 'Brewery' %>
    <%= select_tag(:brewery_id, options_for_select(@breweries), :prompt => "Select a Brewery") %>
    <%= f.input :name, label: 'Beer Name'%>
    <%= f.input :description %>
    <%= f.button :submit, class: 'btn btn-custom' %>
<% end %>

app/views/beers/edit.html.erb
<div class="col-md-6 col-md-offset-3">
    <div class="edit-beer-form">
                
        <h1>Edit <%= @beer.name %></h1>
        
        <%= simple_form_for @beer, :html => { multipart: true } do |f| %>
            <%= f.label :category_id, 'Category' %>
            <%= f.select :category_id, @categories %><br />
            <%= f.label :brewery_id, 'Brewery' %>
            <%= f.select :brewery_id, @breweries %>
            <%= f.file_field :beer_img %>
            <%= f.input :name, label: 'Beer Name'%>
            <%= f.input :description %>
            <%= f.button :submit, class: 'btn btn-custom' %>
        <% end %>
        
    </div>
</div>

app/views/beers/index.html.erb
<% if @beers.count == 0 %>

    <h1>There are not beers currently in this category.</h1>
    
<% else %>
    
    <% if params[:category].blank? == false %>
        <h1 class="current-category"><%= pluralize(@beers.count, params[:category])%></h1>
    <% end %>
    
    <div class="row">
    
        <% @beers.each do |beer| %>
            <div class="col-md-3">
                <div class="beer">
                    <a href="/beers/<%= beer.id %>">
				    	<%= image_tag beer.beer_img.url(:beer_index), class: 'beer-img' %>
			    	</a>
				</div>
            </div>
        <% end %>
    
    </div>

<% end %>

app/views/beers/new.html.erb
<div class="col-md-6 col-md-offset-3">
    <div class="new-beer-form">
        <h1>New Beer</h1>

        <%= render 'form' %>
    </div>
</div>

app/views/beers/show.html.erb
<div class="row">
    <div class="col-md-4">
        <div class="beer-show">
            <%= image_tag(@beer.beer_img.url(:beer_show), class: 'beer-img') %>
        </div>
    </div>
    <div class="col-md-8">
        <div class="beer-info">
            <h2 class="beer-title"><%= @beer.name %></h2>
            <h3 class="beer-category">
                <%= link_to @beer.category.name, beers_path(category: @beer.category.name) %> - 
                <%= link_to @beer.brewery.name, beers_path(brewery: @beer.brewery.name) %>
            </h3>
            <h2 class="avg-rating">Average Rating</h2>
            <div class="average-review-rating" data-score="<%= @average_review %>"></div>
            <span class="number-of-reviews">Based on <%= pluralize(@beer.reviews.count, 'review') %>.</span>
            <p class="beer-desc"><%= @beer.description %></p>
            <div class="links btn-group">
    <% if user_signed_in? %>
        <% if @beer.user_id == current_user.id %>
            <%= link_to 'Edit', edit_beer_path(@beer), class: 'btn btn-custom' %> 
            <%= link_to 'Delete', @beer, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-custom' %>
        <% end %>
    <% end %>
    <%= link_to 'Back', root_path, class: 'btn btn-custom' %>
</div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="reviews">
            <h1>Reviews</h1>
            <%= render @beer.reviews %>
            <div>
                <%= link_to 'Write a review', new_beer_review_path(@beer), class: 'btn-custom'%>
            </div>
        </div>
    </div>
</div>



<script>
    $('.review-rating, .average-review-rating').raty({
        readOnly: true,
        score: function(){
            return $(this).attr('data-score');
        },
        path: '/assets/'
    });
</script>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <%= link_to 'Brew Review', root_path, class: "navbar-brand"%>
        </div>
        
        <ul class="nav navbar-nav">
            <% if user_signed_in? %>
                <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
            <% else %>
                <li><%= link_to 'Sign Up', new_user_registration_path %></li>
                <li><%= link_to 'Log In', new_user_session_path %></li>
            <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                    <% Category.all.each do |category| %>
                        <li class="<%= 'active' if params[:category] == category.name %>">
                            <%= link_to category.name, beers_path(category: category.name), class: 'link' %>
                        </li>
                    <% end %>
                </ul>
            </li>
            <% if user_signed_in? %>
                <li><%= link_to 'Add Beer', new_beer_path %></li> 
            <% end %>
        </ul>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= render 'layouts/navbar' %>

  <div class="container">
    <% if flash[:notice ]%>
      <div class="alert alert-success text-center" role="alert"><%= notice %></div>
    <% end %>
    <% if flash[:alert ]%>
      <div class="alert alert-danger text-center" role="alert"><%= alert %></div>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@beer, @beer.reviews.build]) do |f| %>
    <div id="rating-form">
        <label>Rating</label>
    </div>
    <%= f.input :comment %>
    <%= f.button :submit, class: 'btn btn-custom' %>
<% end %>

<script>
    $('#rating-form').raty({
        path:'/assets/',
        scoreName:'review[rating]'
    });
</script>

app/views/reviews/_review.html.erb
<div class="review">
    <div class="review-rating" data-score="<%= review.rating %>"></div>
    <p class="review-comment"><%= review.comment %></p>
    <p class="reviewer">by <%= User.find_by(id: review.user_id).username%></p>
    <% if user_signed_in? %>
        <% if review.user_id == current_user.id %>
            <div class="links btn-group">
                <%= link_to 'Edit', edit_beer_review_path(review.beer, review), class: "btn btn-custom" %>
                <%= link_to 'Delete', beer_review_path(review.beer, review), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>
            </div>
        <% end %>
    <% end %>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">
    <div class="edit-beer-form">
        
        <h1>Edit Review</h1>
        
        <%= simple_form_for([@beer, @review]) do |f| %>
            <div id="rating-form">
                <label>Rating</label>
            </div>
            <%= f.input :comment %>
            <%= f.button :submit, class: 'btn btn-custom' %>
        <% end %>

    </div>
</div>


<script>
    $('#rating-form').raty({
        path:'/assets/',
        scoreName:'review[rating]'
    });
</script>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">
    <div class="edit-beer-form">
        
        <h1>New Review for <%= @beer.name %></h1>
        
        <%= render 'form' %>
    </div>
</div>